### ISSUE TITLE
procedure still working?

### ISSUE THREAD

**Issue by nnako** [nuncjo/cython-installation-windows#1]
Hi @nuncjo , I was wondering if the procedure you described for successfully installing Cycton and compiler tools on Windows operating system is still valid in 2024. Would you be willing to review and update your information presented here?

**Comment by nuncjo** [comment]
That description has 9 years. I guess that it's not valid for newer Python versions, a lot has changed. It could be useful for someone that was frozen in time with old Windows and Python 3.4. I don't have any plans for update this description, hope that Cython documentation is better nowdays or if not, doesn't AI knows everything now  :)
